 spring:
    datasource:
      url: jdbc:h2:mem:phone_book;DB_CLOSE_DELAY=-1
      username: admin
      password:

    jpa:
      properties:
        hibernate:
          ddl-auto: create


    h2:
      console:
        enable: true
        path: /h2
        settings:
          trace: true
          web-allow-others: true

    liquibase:
#      enabled: false
      change-log: classpath:/db/changelog/db.changelog-master.yaml