 spring:
    datasource:
      url: jdbc:mysql://localhost:3306/phone_book
      username: root
      password: root
    jpa:
      hibernate.ddl-auto: create
      generate-ddl: true
      show-sql: true
